### ISSUE TITLE
Audio stuttering

### ISSUE THREAD

**Issue by PlutoX86** [OpenEmu/4DO-Core#3]
Somehow the audio buffering has been changed some time ago. I know it's not really that important right now, since the core has been deprecated/removed,.. but is there a possibility that someone could tell me how/why the audio is stuttering? Or, at least how "i" could fix it?. (No problem editing some files and compile OE 2.0.8 on Mojave 10.14.5)

I really enjoyed playing Battle Chess and Road Rash with my dad on my mac.. (and yeah, that's why i ask).

**Comment by trapexit** [comment]
May want to look at RetroArch. The 4DO core is actively maintained (though I'll admit I've not given it much attention recently.)

Alternatively I believe both those games are available on PSX (and with Road Rash has better performance without overclocking the emulated CPU).

**Comment by PlutoX86** [comment]
I guess i better close this issue because it's kinda irrelevant anyway. Since the latest SDK commits i figured "double frameSampleCount = [self audioSampleRateForBuffer:index] * **0.2**" would do the trick for me.
